=== cn-org-pbccrc/bwfz/packet-simulation/packet-simulation-web/src/main/webapp/xmlTemplate/sjcj.001.001.02.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="std:rims:2015:tech:xsd:sjcj.001.001.01"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="std:rims:2015:tech:xsd:sjcj.001.001.01"
	elementFormDefault="qualified">
	<xs:element name="Document" type="Document"/>
	<xs:complexType name="Document">
		<xs:sequence>
			<xs:element name="AgreEffMessg" type="BsiInformation"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="BsiInformation">
		<xs:sequence>
			<xs:element name="AgreIDSec" type="IdMod"/>
			<xs:element name="AgreSumSec" type="SumMod"/>
			<xs:element name="GuarSec" type="GuaMod"/>
			<xs:element name="IntRatSec" type="IntRaMod"/>
			<xs:element name="AgreStaSec" type="StaMod"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="IdMod">
		<xs:sequence>
			<xs:element name="AgreID" type="Max40Text"/>
			<xs:element name="OrgID" type="Exact18TextType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="Max40Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="40"/>
			<xs:whiteSpace value="replace"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Exact18TextType">
		<xs:restriction base="xs:string">
			<xs:length value="18"/>
			<xs:whiteSpace value="replace"/>
			<xs:pattern value="[A-Z]\d{16}[A-Z0-9]"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="SumMod">
		<xs:sequence>
			<xs:element name="AgreNum" type="Max40Text"/>
			<xs:element name="InfAgen" type="InfAgenType" maxOccurs="unbounded"/>
			<xs:element name="ReDate" type="ISODate"/>
			<xs:element name="EfDate" type="ISODate"/>
			<xs:element name="DeDate" type="ISODate"/>
			<xs:element name="GuaWa" type="Exact1NumericText"/>
			<xs:element name="BusiType" type="Exact1NumericText"/>
			<xs:element name="CreLinCur" type="Exact3Text"/>
			<xs:element name="CreLinAm" type="Max10NumericText"/>
			<xs:element name="CreLinAdjDate" type="ISODate" minOccurs="0"/>
			<xs:element name="CreLinCir" type="Exact1NumericText"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="InfAgenType">
		<xs:sequence>
			<xs:element name="BorrAgen" type="AgenType"/>
			<xs:element name="CreAgen" type="AgenType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AgenType">
		<xs:sequence>
			<xs:element name="Nam" type="Max80Text" minOccurs="0"/>
			<xs:element name="IDType" type="Exact1NumericText"/>
			<xs:element name="IDNum" type="Max18Text"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="Max80Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="80"/>
			<xs:whiteSpace value="replace"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max18Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="18"/>
			<xs:whiteSpace value="replace"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Exact1NumericText">
		<xs:restriction base="xs:string">
			<xs:length value="1"/>
			<xs:whiteSpace value="replace"/>
			<xs:pattern value="[1-9ABCX]"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ISODate">
		<xs:restriction base="xs:date"/>
	</xs:simpleType>
	<xs:simpleType name="Exact3Text">
		<xs:restriction base="xs:string">
			<xs:length value="3"/>
			<xs:pattern value="[A-Z]{3}|\d{3}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max10NumericText">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="10"/>
			<xs:pattern value="[0-9]{1,10}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="GuaMod">
		<xs:sequence>
			<xs:element name="GuaAgreNum" type="Max40Text"/>
			<xs:element name="GuaSta" type="Exact1NumericText"/>
			<xs:element name="GuaWa" type="Exact1NumericText"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="IntRaMod">
		<xs:sequence>
			<xs:element name="IntRatRef" type="Exact1NumericText"/>
			<xs:element name="IntRatChRat" type="Max5Text"/>
			<xs:element name="IntRatChWa" type="Exact1NumericText"/>
			<xs:element name="IntRatChFre">
				<xs:simpleType>
					<xs:restriction base="Exact1NumericText">
						<xs:whiteSpace value="replace"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="Max5Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="5"/>
			<xs:whiteSpace value="replace"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="StaMod">
		<xs:sequence>
			<xs:element name="AgreSta" type="Exact1NumericText"/>
			<xs:element name="AgreStaChDate" type="ISODate"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== cn-org-pbccrc/bwfz/packet-simulation/packet-simulation-web/src/main/webapp/xmlTemplate/sjcj.001.001.02.xml
<?xml version="1.0" encoding="UTF-8"?>
<Document xmlns="std:rims:2015:tech:xsd:sjcj.001.001.01"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="std:rims:2015:tech:xsd:sjcj.001.001.01 file:/C:/Users/keji/Desktop/sjcj.001.001.02.xsd">
<AgreEffMessg>
<AgreIDSec>
<AgreID>AgreID0</AgreID>
<OrgID>A00000000000000000</OrgID>
</AgreIDSec>
<AgreSumSec>
<AgreNum>AgreNum0</AgreNum>
<InfAgen>
<BorrAgen>
<Nam>Nam0</Nam>
<IDType>1</IDType>
<IDNum>IDNum0</IDNum>
</BorrAgen>
<CreAgen>
<Nam>Nam1</Nam>
<IDType>1</IDType>
<IDNum>IDNum1</IDNum>
</CreAgen>
</InfAgen>
<InfAgen>
<BorrAgen>
<Nam>Nam2</Nam>
<IDType>1</IDType>
<IDNum>IDNum2</IDNum>
</BorrAgen>
<CreAgen>
<Nam>Nam3</Nam>
<IDType>1</IDType>
<IDNum>IDNum3</IDNum>
</CreAgen>
</InfAgen>
<ReDate>2006-05-04</ReDate>
<EfDate>2006-05-04</EfDate>
<DeDate>2006-05-04</DeDate>
<GuaWa>1</GuaWa>
<BusiType>1</BusiType>
<CreLinCur>AAA</CreLinCur>
<CreLinAm>0</CreLinAm>
<CreLinAdjDate>2006-05-04</CreLinAdjDate>
<CreLinCir>1</CreLinCir>
</AgreSumSec>
<GuarSec>
<GuaAgreNum>GuaAgreNum0</GuaAgreNum>
<GuaSta>1</GuaSta>
<GuaWa>1</GuaWa>
</GuarSec>
<IntRatSec>
<IntRatRef>1</IntRatRef>
<IntRatChRat>IntRa</IntRatChRat>
<IntRatChWa>1</IntRatChWa>
<IntRatChFre>1</IntRatChFre>
</IntRatSec>
<AgreStaSec>
<AgreSta>1</AgreSta>
<AgreStaChDate>2006-05-04</AgreStaChDate>
</AgreStaSec>
</AgreEffMessg>
</Document>
